# Generated by Django 5.0.6 on 2024-05-30 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_user_city_user_img_user_info_alter_user_first_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='info',
            new_name='about',
        ),
    ]
