# Generated by Django 5.0.6 on 2024-05-15 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='articles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('subtitle', models.CharField(max_length=200, verbose_name='Подзаголовок')),
                ('content', models.TextField(verbose_name='Текст статьи')),
                ('date', models.DateField(verbose_name='Дата публикации')),
            ],
        ),
    ]
